const serviceRouter = require('./home/services')
const serviceItemRouter = require('./home/serviceItems')
const employeeRouter = require('./home/employees')
const employeeItemRouter = require('./home/employeeItems')
const endowRouter = require('./home/endows')
const endowItemRouter = require('./home/endowItems')
const commitRouter = require('./home/commits')
const commitItemRouter = require('./home/commitItems')
const provinceRouter = require('./home/provinces')
const provinceItemRouter = require('./home/provinceItems')
const spaceRouter = require('./home/spaces')
const spaceItemRouter = require('./home/spaceItems')
const storeRouter = require('./home/stores')
const storeItemRouter = require('./home/storeItems')
const hairSalonRouter = require('./about/hairSalons')
const missionRouter = require('./about/missions')
const visionRouter = require('./about/visions')
const visionItemRouter = require('./about/visionItems')
const postRouter = require('./about/posts')
const postItemRouter = require('./about/postItems')

function route(app) {
    app.use('/services', serviceRouter)
    app.use('/service-items', serviceItemRouter)
    app.use('/employees', employeeRouter)
    app.use('/employee-items', employeeItemRouter)
    app.use('/endows', endowRouter)
    app.use('/endow-items', endowItemRouter)
    app.use('/commits', commitRouter)
    app.use('/commit-items', commitItemRouter)
    app.use('/provinces', provinceRouter)
    app.use('/province-items', provinceItemRouter)
    app.use('/spaces', spaceRouter)
    app.use('/space-items', spaceItemRouter)
    app.use('/stores', storeRouter)
    app.use('/store-items', storeItemRouter)
    app.use('/hair-salons', hairSalonRouter)
    app.use('/missions', missionRouter)
    app.use('/visions', visionRouter)
    app.use('/vision-items', visionItemRouter)
    app.use('/posts', postRouter)
    app.use('/post-items', postItemRouter)
}

module.exports = route
