const routes = {
    home: '/',
    about: '/about',
    systemSalon: '/system-salon',
    shineMember: '/shine-member',
    cutHairService: '/dich-vu-cat-toc',
    curlHairService: '/dich-vu-uon-nhuom-duong-toc',
    dyingHairService: '/dich-vu-uon-nhuom-duong-toc#nhuom-toc',
    massageService: '/dich-vu-goi-massage-spa-relax',
    spaService: '/dich-vu-goi-massage-spa-relax#spa',
    earwaxService: '/dich-vu-goi-massage-spa-relax#layraytai',
    question: '/cau-hoi-thuong-gap',
    cosmetics: '/my-pham-va-san-pham',
    primeLocation: '/vi-tri-cua-hang-dac-dia',
    modernEquipment: '/trang-thiet-bi-sieu-hien-dai-cho-trai-nghiem-vuot-troi',
    masterTime: '/my-pham-va-san-pham',
    shineCare: '/shine-care',
    haNoiProvince: '/system-salon?province=62',
    hoChiMinhProvince: '/system-salon?province=1',
    daNangProvince: '/system-salon?province=60',
    policy: '/chinh-sach-bao-mat',
    contactAdvertising: '/contact-advertising',
};

export default routes;
